### ISSUE TITLE
Support for spanish language

### ISSUE THREAD

**Issue by KarthiAru** [fsondej/autocorrect#6]
Hi,

I'm unable to download the dictionary for Spanish language.

```
from autocorrect import Speller
spell = Speller(lang="es")
```

I'm getting the following error when I try this.
```
dictionary for this language not found, downloading...
__________________________________________________
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/site-packages/autocorrect/__init__.py", line 58, in __init__
    self.nlp_data = load_from_tar(lang)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/site-packages/autocorrect/__init__.py", line 48, in load_from_tar
    urlretrieve(url, archive_name, progress.download_progress_hook)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/karthikarumugham/anaconda3/envs/bot/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by fsondej** [comment]
Hi,
Spanish isn't supported yet. You can add it by following instructions in https://github.com/fsondej/autocorrect#adding-new-languages.
