### ISSUE TITLE
pip install autocorrect raises exception related to unexpected keyword argument

### ISSUE THREAD

**Issue by AdamAdLightning** [fsondej/autocorrect#60]
When I run `pip3 install autocorrect` on my local machine, I get the following output.

```Python
Collecting autocorrect
  Using cached autocorrect-2.6.1.tar.gz (622 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Warning: 'classifiers' should be a list, got type 'tuple'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qot3xq2y/autocorrect_c58bf5c1bfca47d58e13f5f1e06c7de0/setup.py", line 3, in <module>
          setup(
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 310, in run
          self.find_sources()
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
          mm.run()
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 544, in run
          self.prune_file_list()
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 610, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/home/<redacted>/.pyenv/versions/3.9.13/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

Not sure how to proceed here.

**Comment by AdamAdLightning** [comment]
Running the following command before installation fixed this: `pip3 install --upgrade packaging`
